#!/usr/bin/env bash
# Atualiza as 45 skills vendorizadas de diegosouzapw/OmniRoute.
#
# Entra o conjunto inteiro: as 45 são referência auto-gerada da API REST e do CLI
# do gateway, não há subconjunto que faça sentido separar. Por isso, diferente do
# update-caveman.sh, aqui NÃO há lista fixa — o script instala o que existir em
# skills/ na origem e remove daqui o que sumir de lá.
#
# O gateway em si (`npm i -g omniroute`, servidor em localhost:20128) NÃO é
# instalado por este script e não tem nada a ver com ele. Mesmo motivo do
# CLI/proxy do caveman: é ferramenta global de máquina, repontua o
# ANTHROPIC_BASE_URL do Claude Code para um proxy local. Decisão separada,
# tomada fora do repo. Sem ele, as 45 skills não têm com o que falar.
#
# O repo da origem tem 433 MB — o clone é raso, sparse e sem blobs, e traz só
# skills/ e a LICENSE.
set -euo pipefail

REPO="https://github.com/diegosouzapw/OmniRoute.git"
REF="${OMNIROUTE_REF:-main}"   # main é o que os raw URLs do README apontam;
                               # o branch default do repo é a release da vez
                               # (release/v3.8.x) e às vezes traz skill a mais.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Toda SKILL.md da origem nasce deste gerador. Serve para duas coisas: recusar
# copiar o que não for skill do OmniRoute, e reconhecer aqui dentro o que veio
# daquele conjunto na hora de podar.
MARKER="generated by src/lib/agentSkills/generator.ts"

echo "→ clonando $REPO @ $REF..."
git clone --quiet --filter=blob:none --sparse --depth 1 --branch "$REF" "$REPO" "$STAGE/omniroute"
# cone mode do sparse-checkout só aceita diretório; a LICENSE vem depois por
# git show, que busca o blob sob demanda (o clone é --filter=blob:none).
git -C "$STAGE/omniroute" sparse-checkout set skills >/dev/null
COMMIT="$(git -C "$STAGE/omniroute" rev-parse HEAD)"

SRC="$STAGE/omniroute/skills"
[ -d "$SRC" ] || { echo "✗ skills/ não existe na origem @ $REF" >&2; exit 1; }

mkdir -p "$ROOT/_config/skills" "$ROOT/.claude/skills"

upstream=()
for dir in "$SRC"/*/; do
  name="$(basename "$dir")"
  file="$dir/SKILL.md"
  [ -f "$file" ] || { echo "✗ skills/$name não tem SKILL.md" >&2; exit 1; }
  # canário: pasta != name: faz o Claude Code ignorar a skill sem avisar
  declared="$(sed -n 's/^name: *//p' "$file" | head -1)"
  [ "$declared" = "$name" ] || { echo "✗ skills/$name declara name: $declared" >&2; exit 1; }
  grep -q "$MARKER" "$file" || { echo "✗ skills/$name não tem o marcador do gerador" >&2; exit 1; }
  upstream+=("$name")
done

[ "${#upstream[@]}" -gt 0 ] || { echo "✗ nenhuma skill encontrada em skills/" >&2; exit 1; }

for name in "${upstream[@]}"; do
  rm -rf "$ROOT/_config/skills/$name"
  cp -R "$SRC/$name" "$ROOT/_config/skills/$name"
  ln -sfn "../../_config/skills/$name" "$ROOT/.claude/skills/$name"
done
echo "  ✓ ${#upstream[@]} skills instaladas"

# Poda: skill que já esteve aqui, carrega o marcador, e sumiu da origem. Sem
# isso ela ficaria para sempre, e o Claude Code continuaria oferecendo uma
# referência que a origem já removeu.
removed=0
for local in "$ROOT/_config/skills"/*/; do
  name="$(basename "$local")"
  [ -f "$local/SKILL.md" ] || continue
  grep -q "$MARKER" "$local/SKILL.md" || continue
  printf '%s\n' "${upstream[@]}" | grep -qx "$name" && continue
  rm -rf "$local" "$ROOT/.claude/skills/$name"
  echo "  – $name removida (não existe mais na origem)"
  removed=$((removed + 1))
done
[ "$removed" -eq 0 ] || echo "  ✓ $removed skill(s) podada(s)"

git -C "$STAGE/omniroute" show HEAD:LICENSE > "$ROOT/_config/skills/LICENSE-omniroute"

echo "✓ commit ${COMMIT:0:12}"
echo "  Anote o commit no ORIGEM.md e reinicie o Claude Code para recarregar."
